RelativeURLs=true
CanonifyURLs=true
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Serverlesspresso Workshop"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

uglyurls=true
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
  description = "Serverlesspresso workshop"
  author = "Ben Smith (https://twitter.com/benjamin_l_s) & James Beswick (https://twitter.com/jbesw)"
  hashCode = "cfcd-1775e06ee4-d3"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableSearch = true
  disableAssetsBusting = true
  disableLanguageSwitchingButton = true
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true

[Languages]
[Languages.en]
title = "Serverlesspresso"
weight = 1
languageName = "English"
